version: 2
jobs:
  Integrate:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      #- image: microsoft/azure-cli
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is 
          - v1-dependencies-

      - run: npm build
      #- run: npm build  
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Unit Tests
          command: |
            echo "SonarQube Scan"     
      - run:
          name: Vulnerability & Quality Scan [Sonarqube]
          command: |
            echo "SonarQube Scan"    
      - run:
          name: Creating Artifacts 
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            tar -zcvf /tmp/artifacts/archive-name.tar.gz *
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2; 
            
      - store_artifacts:
          path:  /tmp/artifacts
          destination: artifact-file

      #- store_artifacts:
       #   path:  /tmp/artifacts
      # run tests!
      #- run: npm run test
           
  Deploy Environments:
    docker:
      - image: circleci/node:jessie-browsers
      
    steps:
      # LOGIN ONTO AZURE WITH EXISTING SERVICE PRINCIPAL
      - run:
          name: Integration Testing  - Provision Infrastructure [LAMP WebApp Stack]
          command: |
            echo "provision Infrastructure"  
      - run:
          name: Integration Testing  - Apply Configuration [LAMP WebApp Stack]
          command: |
            echo "Integration Testing  - Apply Configuration"  
      - run:
          name: Integration Testing  - Deploy
          command: |
            echo "Integration Testing  - Deploy Artifact [WebApp]"  
      - run:
          name: Integration Testing Security Source Scan
          command: |
            echo "Integration Testing Security Source Scan"
      - run:
          name: Integration Testing  - Run Integration Tests
          command: |
            echo "Run Integration Tests" 
      - run:
          name: Integration Testing  - UnProvision Infrastructure [LAMP WebApp Stack]
          command: |
            echo "unprovision Infrastructure"
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium          
          command: java -jar selenium-server-standalone-3.5.3.jar -log selenium.log
          background: true      
      - run:
          name: User Acceptance Testing  - Provision Infrastructure [LAMP WebApp Stack]
          command: |
            echo "provision Infrastructure"  
      - run:
          name: User Acceptance Testing  - Apply Configuration [LAMP WebApp Stack]
          command: |
            echo "User Acceptance Testing  - Apply Configuration"  
      - run:
          name: User Acceptance Testing  - Deploy
          command: |
            echo "User Acceptance Testing  - Deploy Artifact [WebApp]"                                          
  Release:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      # LOGIN ONTO AZURE WITH EXISTING SERVICE PRINCIPALe
      - run:
          name: Production - Cutover Staging Environment to Production 
          command: |
            echo "production Release - DNS Change"                 
workflows:
  version: 2
  provision_build_and_deploy:
    jobs:
     - Integrate 
     - Deploy Environments:
          requires:
            - Integrate 
     - Release to Production:
          type: approval
          requires:
           - Deploy Environments       
