version: 2
jobs:
  Integrate:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      #- image: microsoft/azure-cli
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is 
          - v1-dependencies-

      - run: npm build
      #- run: npm build  
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Unit Tests
          command: |
            echo "SonarQube Scan"     
      - run:
          name: Vulnerability & Quality Scan [Sonarqube]
          command: |
            echo "SonarQube Scan"    
      - run:
          name: Creating Artifacts 
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            tar -zcvf /tmp/artifacts/archive-name.tar.gz *
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2; 
            
      - store_artifacts:
          path:  /tmp/artifacts
          destination: artifact-file

      #- store_artifacts:
       #   path:  /tmp/artifacts
      # run tests!
      #- run: npm run test
           
  Deploy:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      # LOGIN ONTO AZURE WITH EXISTING SERVICE PRINCIPAL 
      - run:
          name: Integration Testing  - Provision Infrastructure [LAMP WebApp Stack]
          command: |
            echo "provision Infrastructur"  
      - run:
          name: Integration Testing  - Apply Configuration [LAMP WebApp Stack]
          command: |
            echo "Integration Testing  - Apply Configuration"  
      - run:
          name: Integration Testing  - Deploy
          command: |
            echo "Integration Testing  - Deploy Artifact [WebApp]"  
      - run:
          name: SIT Security Source Scan
          command: |
            echo "SIT Security Source Scan"                      
  Release:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      # LOGIN ONTO AZURE WITH EXISTING SERVICE PRINCIPALe
      - run: |
          echo "mlogin"             
workflows:
  version: 2
  provision_build_and_deploy:
    jobs:
     - Integrate 
     - Deploy:
          requires:
            - Integrate 
     - Release:
          type: approval
          requires:
           - Deploy       
